services:
  db:
    image: postgres:16-alpine
    container_name: secureapp_db_prod
    restart: no
    environment:
      POSTGRES_USER: secureapp
      POSTGRES_PASSWORD: secureapp
      POSTGRES_DB: secureapp
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secureapp -d secureapp -h 127.0.0.1"]
      interval: 2s
      timeout: 2s
      retries: 30
      start_period: 5s
    networks:
      - secure_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: secureapp_backend_prod
    restart: no
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://secureapp:secureapp@db:5432/secureapp
      JWT_SECRET: "mon_secret_jwt_super_long_et_complexe"
      JWT_EXPIRATION: "15m"
      REFRESH_EXPIRATION: "7d"
      FRONTEND_URL: http://localhost:8080
    volumes:
      - ./backend/certs:/app/certs:ro
    ports:
      - "4000:4000"
    networks:
      - secure_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: secureapp_frontend_prod
    restart: no
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - secure_net

  adminer:
    image: adminer:latest
    container_name: secureapp_adminer_prod
    restart: no
    depends_on:
      - db
    ports:
      - "8082:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - secure_net

volumes:
  db_data:

networks:
  secure_net:
